language: python
matrix:
  include:
    - os: linux
      python: 3.4   # When support for 3.4 is removed unpin the PyYAML version below.

# command to install dependencies
install:
  - source .travis/install.sh
  - python --version
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then python -m pip install PyYAML==5.2; fi # Forcing PyYAML 5.2 while we retain Python 3.4 support PyYAML 5.3 and higher does not support Python 3.4
  - python -m pip install $PIP_USER_FLAG PyYAML argparse certifi rospkg vcstools catkin_pkg python-dateutil rosdistro
  - python -m pip install $PIP_USER_FLAG -e .
  - python -m pip install $PIP_USER_FLAG nose coverage flake8 mock codecov
# command to run tests
script:
  - python -m nose --with-coverage --cover-package=rosdep2 --with-xunit test
after_script:
  - python -m codecov
notifications:
  email: false
