language: python
matrix:
  include:
    - os: linux
      python: 2.6
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: osx
      language: generic
      env: PYTHON_INSTALLER=brew
    - os: osx
      language: generic
      env: PYTHON_INSTALLER=pyenv TRAVIS_PYTHON_VERSION=2.7.14
    - os: osx
      language: generic
      env: PYTHON_INSTALLER=pyenv TRAVIS_PYTHON_VERSION=3.6.4

# command to install dependencies
install:
  - source .travis/install.sh
  - python --version
  - pip install PyYAML argparse rospkg vcstools catkin_pkg python-dateutil rosdistro
  - pip install -e .
  - pip install nose coverage flake8 mock codecov
# command to run tests
script:
  - pip --version
  - pip list
  - nosetests --with-coverage --cover-package=rosdep2 --with-xunit test
after_script:
  - codecov
notifications:
  email: false
