language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install argparse catkin-pkg rosdistro rospkg PyYAML setuptools
# command to run tests
script:
# This package doesn't have tests yet.
  - true # - nosetests -s --tests test
notifications:
  email: false
